name: "PHP Test"
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo_mysql
      - run: composer install
